project:
  type: book
  output-dir: ../docs/q/

book:
  title: "GatAI v. X-Mas-3"
  author: "Aleksander Dietrichson, PhD"
  date: "8/23/2023"

  chapters:
    - index.qmd
    - x-mas-3-description.qmd
    - abstracting-x-mas-3.qmd
    - model-training.qmd
    - full-board-strategies.qmd
    - computer-vision-model.qmd
    - showdown.qmd
    - references.qmd
  appendices:
     - implementation-and-scalability.qmd
     - business-case.qmd

bibliography: references.bib
#csl: https://www.zotero.org/styles/chicago-fullnote-bibliography-16th-edition
# csl: nature.csl
# reference-location: margin
# citation-location: margin
footnote-location: margin
format:
  html:
    theme: cyborg
#    theme: cosmo
    number-depth: 2
    monofont: "JetBrains Mono"
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=JetBrains Mono" type="text/css"/>

  
#    theme: slate
#    theme: lux

editor: visual

