---
title: "Windowing and Sliding"
author: "Aleksander Dietrichson"
format: html
editor: visual
---

Since we are operating on simplified sub-boards, and part of our strategy is to window the playing-board we implemented functions to *window* a board, i.e. subdivide it into smaller pieces for analysis. When moves are suggested for the sub-division we need to *slide* these moves over on the real playing board (i.e. the larger one).

```{r}
library(xmas3)
library(ggplot2)
```

```{r}
#| label: fig-window-example
#| fig-cap: "Example of windowing"
#| warning: false
set.seed(200)
#B <- xmas3board(9999999999999932209486743616279764617084419440640,c(6,10))
B <- xmas3board(100000000000000,c(6,10))
p <- plot(B)
p<-p+ggplot2::annotate("rect",xmin=2,ymin=2,ymax=4,xmax=5, color="red", alpha=.2)
p
```

```{r}

B2 <- window(B, from = c(3,3),c(2,3))
my_move <- "B1A1"
my_move2 <- "A2A1"
plot(B2) %>%
  add_move(my_move) %>% 
  add_move(my_move2)


```

```{r}

p %>% 
  add_move(slide_move(my_move,B2)) %>% 
  add_move(slide_move(my_move2,B2))
```

```{r}

slide_move(my_move, B2)
slide_move(my_move2, B2)
```
